name: frontend

description: "Aplicação mobile para gestão de dispensário eletrônico de medicamentos."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.6
  flutter_chat_ui: ^1.6.13
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  file_picker: ^8.0.3
  mime: ^1.0.5
  uuid: ^4.4.0
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

assets:
  - .env
  - assets/messages.json